server:
  port: 8080

spring:
  application:
    name: course-system
  datasource:
    url: jdbc:mysql://localhost:3306/course_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: dev
    password: dev123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.sy.course_system.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

recommend:
  service:
    url: http://localhost:8000